### ISSUE TITLE
AWS Cli installation issue

### ISSUE THREAD

**Issue by SubatomicHero** [Alfresco/chef-commons#13]
The installation of the aws cli is intermittent, sometimes it installs sometimes it doesnt. This needs to be installed 100% of the time.

**Comment by enzor** [comment]
Hi Martin.

To install aws_cli with chef-commons, you should set the parameter 
```
default['commons']['install_awscli']
```

to `true` inside your wrapper cookbook, then call this recipe directly ( as `commons::awscli` ) or the ec2_tagging recipe ( commons::ec2_tagging) as the latter already calls the awscli installation.

Hope this was of help!

**Comment by enzor** [comment]
Said that, I talked with @marcomancuso and told me that the problem you are experiencing are coming from a branch of our colleague, which is not in your main develop branch.

Could you investigate that issue and try to replicate?

**Comment by ghost** [comment]
Project not supported so moving it to AlfrescoLabs, archiving it and closing all issues
