### ISSUE TITLE
chef_version?

### ISSUE THREAD

**Issue by mtwallach** [Alfresco/chef-commons#23]
Why is chef-commons bound to Chef V12? Just wondering as 13 is being used by a customer and wondering how to maybe get around that

**Comment by marcomancuso** [comment]
@mtwallach all our cookbooks are Chef V12 compatible, Chef13 is still very new (15days), and it would possibly require a bit of effort to make our code compatible.
As you can see from https://discourse.chef.io/t/chef-client-13-released/10735 there is a long list of Backwards Compatibility Breaks

**Comment by nicdoye** [comment]
I see Travis is running Chef 13, so it bails out.

**Comment by ghost** [comment]
Project not supported so moving it to AlfrescoLabs, archiving it and closing all issues
